### PR TITLE
Fixed typo, reduced if-else checking and other improvements

### PR DESCRIPTION
**Pull request by Omkar76**
Fixes include : 

+ Fixed typo Cencal -> Cancel in  7c06f4b21df0270e7eb5f5e160189007c3435df3

+ Fixed accessibility issue. `htmlFor` requires  a value that is `id` of element to be associated with it. `id`'s were missing in some cases. in some points wrong value was provided. I've fixed that in 3f08c582112f1ee2fa5e066e58359a487f56ae15
read[ SO answer](https://stackoverflow.com/jobs/companies?so_medium=StackOverflow&so_source=SiteNav) for details.

+ Reduced if else checking for values of `class` and `section` by  using type assertion e9f4f2a8528f4cf86a588cfd354111b224a30fcb

+ Changed title, meta description and meta theme-color. d0e6de8bdad8e7a1b6930d92e03d83784da4e8a2

Nice app btw.

### CODE REVIEW

**Comment by vivek80801** [comment]
Thanks for contribution.

**Comment by vivek80801** [comment]
Your pull request is not working om my http://localhost:3000. Is this working for You?

**Comment by Omkar76** [comment]
@vivek80801 ,
Yes, it's working.

I used `yarn start` from root directory and it automatically launches app in firefox (default browser) at http://localhost:3000/

**Comment by vivek80801** [comment]
@Omkar76 

Sorry for misconvenience,

I had mixed package managers. This Project was created with yarn and I had install dependencies  with npm and started with npm. so, I was getting that error. It was my mistake. 

Thank You for your time.

**Pull request merged**
